######### Generated by Gemini and other AI models #########


#############
#### ALL PASS ######
.text
    # Initialize registers
    addi x1, zero, 10   # x1 = 10
    addi x2, zero, -5   # x2 = -5 (Check sign extension logic)
    
    # Simple Arithmetic
    add x3, x1, x2      # x3 = 5
    sub x4, x1, x2      # x4 = 15 (10 - (-5))
    or  x5, x1, x2      # x5 = Bitwise OR
    and x6, x1, x2      # x6 = Bitwise AND
    
    # Helper to stop execution in Ripes (loops forever)
    end_loop_1:
    beq zero, zero, end_loop_1


nop
nop
nop
nop
nop
nop
nop
nop
nop
nop
nop



#############
#### ALL PASS ######
.data
    test_val: .word 0xDEADBEEF

.text
    la x10, test_val
    lw x1, 0(x10)       # Load 0xDEADBEEF into x1
    
    # HAZARD 1: Load-Use Hazard
    # Even with forwarding, a Load-Use usually requires 1 stall.
    # If you don't stall here, x2 gets garbage.
    addi x2, x1, 1      # x2 = x1 + 1
    
    # HAZARD 2: EX-EX Dependency
    # x3 depends on x2 which is calculated in the previous cycle.
    add x3, x2, x1      # x3 = x2 + x1
    
    # HAZARD 3: MEM-EX Dependency (Distance 2)
    add x4, x3, x1      # x4 depends on x3


nop
nop
nop
nop
nop
nop
nop
nop
nop
nop
nop



###########
####### ALL PASS #######

.text
    addi x1, zero, 5    # Counter = 5
    addi x2, zero, 0    # Accumulator = 0
    
loop:
    beq x1, zero, exit  # If x1 == 0, exit
    add x2, x2, x1      # x2 += x1
    addi x1, x1, -1     # Decrement counter
    
    # Intentional junk to test flushing
    # If your simulator executes this during a taken branch, you failed.
    beq zero, zero, loop
    
    addi x5, zero, 999  # SHOULD NOT EXECUTE UNTIL EXIT
    
exit:
    addi x6, zero, 1    # Finished


nop
nop
nop
nop
nop
nop
nop
nop
nop
nop


#########
##### ALL PASS ####
.data
    float_pi:  .float 3.14159
    
.text
    # Load addresses
    la x10, float_pi
    la x11, double_pi

    flw f1, 0(x10)      # Load float
    fadd.s f2, f1, f1   # f2 = 2 * pi (approx)
    
    # Mixed Hazard: Integer to Float move
    # This tests connection between Int regfile and Float regfile
    addi x5, zero, 10
    fcvt.s.w f5, x5     # Convert Int 10 to Float 10.0 in f5

nop
nop
nop
nop
nop
nop
nop